name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest-alpine

    steps:
    - uses: actions/checkout@v4
    - name: Install turbojpeg
      run: apk add --no-cache libjpeg-turbo-dev libjpeg-turbo
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
